### ISSUE TITLE
Test:  E2E gRPC transcode JSON fuzz test failed.

### ISSUE THREAD

**Issue by qiwzhang** [cloudendpoints/esp#553]
Starting grpc transcode fuzz test at Tue Feb 26 14:00:26 UTC 2019.
Use http to connect: esp.test-0fd2725-gke-tight-http2-echo-6a47-1902261346.svc.cluster.local:8080
Use http to connect: esp.test-0fd2725-gke-tight-http2-echo-6a47-1902261346.svc.cluster.local:8090
Running /echo JSON fuzz tests...
Traceback (most recent call last):
  File "./esp_transcoding_fuzz_test.py", line 247, in <module>
    esp_test.run_all_tests()
  File "./esp_transcoding_fuzz_test.py", line 229, in run_all_tests
    self._run_fuzz_tests()
  File "./esp_transcoding_fuzz_test.py", line 208, in _run_fuzz_tests
    self._run_json_fuzz_tests('/echo', 4, 2)
  File "./esp_transcoding_fuzz_test.py", line 193, in _run_json_fuzz_tests
    fuzzer.run(lambda json: self._request(url, None, json, [200, 400], True))
  File "./esp_transcoding_fuzz_test.py", line 69, in run
    self._run(template, f)
  File "./esp_transcoding_fuzz_test.py", line 61, in _run
    self._run(template.replace('FUZZ', token, 1), f)
  File "./esp_transcoding_fuzz_test.py", line 61, in _run
    self._run(template.replace('FUZZ', token, 1), f)
  File "./esp_transcoding_fuzz_test.py", line 64, in _run
    f(template)
  File "./esp_transcoding_fuzz_test.py", line 193, in <lambda>
    fuzzer.run(lambda json: self._request(url, None, json, [200, 400], True))
  File "./esp_transcoding_fuzz_test.py", line 173, in _request
    response = esp_utils.Response(self._conn.getresponse())
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer

**Comment by qiwzhang** [comment]
v1.28.x doesn't have this problem.  Just run the e2e test 

All load tests are successful.
Starting grpc transcode fuzz test at Wed Feb 27 02:50:19 UTC 2019.
Use http to connect: esp.test-250565b-gke-tight-http2-echo-d5bd-1902270235.svc.cluster.local:8080
Use http to connect: esp.test-250565b-gke-tight-http2-echo-d5bd-1902270235.svc.cluster.local:8090
Running /echo JSON fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 2772, unexpected errors - 0
Running /echostream JSON fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 5544, unexpected errors - 0
Running /echo query param fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 5810, unexpected errors - 0
Running URL path fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 6068, unexpected errors - 0
Running /echo JSON fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 8840, unexpected errors - 0
Running /echostream JSON fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 11612, unexpected errors - 0
Running /echo query param fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 11878, unexpected errors - 0
Running URL path fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 12136, unexpected errors - 0
Running /echo JSON fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 14908, unexpected errors - 0
Running /echostream JSON fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 17680, unexpected errors - 0
Running /echo query param fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 17946, unexpected errors - 0
Running URL path fuzz tests...
Checking for crashes...
[92mNo crashes detected.[0m
Fuzz test results so far: total - 18204, unexpected errors - 0
[92mFuzz test passed.[0m

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/pull/556

**Comment by qiwzhang** [comment]
This is introduced by https://github.com/cloudendpoints/esp/pull/530
