### ISSUE TITLE
SSL error when deploying with Istio sidecar injection enabled

### ISSUE THREAD

**Issue by LewisTheobald** [cloudendpoints/esp#643]
Currently using Istio with rate limiting rules, however we're unable to get our deployment to build properly with sidecar injection enabled. Without, it builds without a problem however once enabled we get:

```
2019-07-14 19:07:45.801 BST
INFO:Constructing an access token with scope https://www.googleapis.com/auth/service.management.readonly
E 2019-07-14T18:07:45.803704394Z INFO:Service account email: X@Y.iam.gserviceaccount.com
 
E 2019-07-14T18:07:45.842989077Z INFO:Refreshing access_token
 
E 2019-07-14T18:07:45.863126576Z Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 365, in execute
  File ".bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 408, in _execute
  File ".bootstrap/_pex/pex.py", line 466, in execute_entry
  File ".bootstrap/_pex/pex.py", line 471, in execute_module
  File "/usr/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "start_esp/start_esp.py", line 1061, in <module>
  File "start_esp/start_esp.py", line 343, in fetch_service_config
  File "start_esp/fetch_service_config.py", line 151, in make_access_token
  File "/root/.pex/install/oauth2client-4.1.3-py2.py3-none-any.whl.289a6efc12c558f2f0ae1841479ec3ee7a783c1b/oauth2client-4.1.3-py2.py3-none-any.whl/oauth2client/client.py", line 663, in get_access_token
 
E 2019-07-14T18:07:45.864885572Z     self.refresh(http)
 
E 2019-07-14T18:07:45.864978614Z   File "/root/.pex/install/oauth2client-4.1.3-py2.py3-none-any.whl.289a6efc12c558f2f0ae1841479ec3ee7a783c1b/oauth2client-4.1.3-py2.py3-none-any.whl/oauth2client/client.py", line 545, in refresh
 
E 2019-07-14T18:07:45.865192183Z     self._refresh(http)
 
E 2019-07-14T18:07:45.865274291Z   File "/root/.pex/install/oauth2client-4.1.3-py2.py3-none-any.whl.289a6efc12c558f2f0ae1841479ec3ee7a783c1b/oauth2client-4.1.3-py2.py3-none-any.whl/oauth2client/client.py", line 749, in _refresh
 
E 2019-07-14T18:07:45.865473352Z     self._do_refresh_request(http)
 
E 2019-07-14T18:07:45.865543890Z   File "/root/.pex/install/oauth2client-4.1.3-py2.py3-none-any.whl.289a6efc12c558f2f0ae1841479ec3ee7a783c1b/oauth2client-4.1.3-py2.py3-none-any.whl/oauth2client/client.py", line 780, in _do_refresh_request
 
E 2019-07-14T18:07:45.865745835Z     body=body, headers=headers)
 
E 2019-07-14T18:07:45.865815270Z   File "/root/.pex/install/oauth2client-4.1.3-py2.py3-none-any.whl.289a6efc12c558f2f0ae1841479ec3ee7a783c1b/oauth2client-4.1.3-py2.py3-none-any.whl/oauth2client/transport.py", line 282, in request
 
E 2019-07-14T18:07:45.866000915Z     connection_type=connection_type)
 
E 2019-07-14T18:07:45.866089304Z   File "/root/.pex/install/httplib2-0.13.0-py2-none-any.whl.f7b2ff9b447b5741fa19aab52032ab1c7db17f35/httplib2-0.13.0-py2-none-any.whl/httplib2/__init__.py", line 2135, in request
 
E 2019-07-14T18:07:45.866471582Z     cachekey,
 
E 2019-07-14T18:07:45.866547796Z   File "/root/.pex/install/httplib2-0.13.0-py2-none-any.whl.f7b2ff9b447b5741fa19aab52032ab1c7db17f35/httplib2-0.13.0-py2-none-any.whl/httplib2/__init__.py", line 1796, in _request
 
E 2019-07-14T18:07:45.866851611Z     conn, request_uri, method, body, headers
 
E 2019-07-14T18:07:45.866949601Z   File "/root/.pex/install/httplib2-0.13.0-py2-none-any.whl.f7b2ff9b447b5741fa19aab52032ab1c7db17f35/httplib2-0.13.0-py2-none-any.whl/httplib2/__init__.py", line 1701, in _conn_request
 
E 2019-07-14T18:07:45.867280486Z     conn.connect()
 
E 2019-07-14T18:07:45.867291943Z   File "/root/.pex/install/httplib2-0.13.0-py2-none-any.whl.f7b2ff9b447b5741fa19aab52032ab1c7db17f35/httplib2-0.13.0-py2-none-any.whl/httplib2/__init__.py", line 1411, in connect
 
E 2019-07-14T18:07:45.867523523Z     raise SSLHandshakeError(e)
 
E 2019-07-14T18:07:45.867657431Z httplib2.SSLHandshakeError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661)
 ```

I've tried adding:

```
- mountPath: /etc/nginx/ssl/nginx.crt
  name: istio-ingressgateway-certs
  subPath: tls.crt
  readOnly: true
- mountPath: /etc/nginx/ssl/nginx.key
  name: istio-ingressgateway-certs
  subPath: tls.key
  readOnly: true
```

But that gave the same error.

I tried running with `--generate-generate_self_signed_cert` but that also didn't work. I've setup SSL on port 443 with `ssl_port=443` and `containerPort: 443`

With Istio sidecar injection disabled, it runs normally:

```
E 2019-07-14T18:21:44.360676712Z INFO:Constructing an access token with scope https://www.googleapis.com/auth/service.management.readonly
E 2019-07-14T18:21:44.362522561Z INFO:Service account email: X@Y.iam.gserviceaccount.com
E 2019-07-14T18:21:44.401245313Z INFO:Refreshing access_token
E 2019-07-14T18:21:44.460607215Z INFO:Fetching the service config ID from the rollouts service
E 2019-07-14T18:21:45.220485588Z INFO:Fetching the service configuration from the service management service
E 2019-07-14T18:21:46.046356174Z INFO:Attribute zone: europe-west2-a
E 2019-07-14T18:21:46.049283034Z INFO:Attribute project_id: X
E 2019-07-14T18:21:46.054935490Z INFO:Attribute kube_env: KUBE_ENV
 ```

**Comment by LewisTheobald** [comment]
Also, when I remove `ssl_port` and `--generate_self_signed_cert` entirely, it produces the same result and fails over the SSL handshake. At a stalemate to get around this.

**Comment by qiwzhang** [comment]
It seems that Istio is blocking ESP to talk to Google SeviceManagement [service](https://servicemanagement.googleapis.com). 

ESP needs to talk to it to get the service config.
